language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
script:
  - py.test --cov=. --doctest-modules -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
env:
  - NUMBA_DISABLE_JIT=1